hl.on("hyprland.start", function()
    hl.exec_cmd("dex --autostart --environment Hyprland")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/start-gnome-keyring.sh")
    hl.exec_cmd("pkill -9 kwalletd5 kwalletd6 2>/dev/null || true")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-hypr-layout --restore --quiet")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-snappy-switcher daemon")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-battery-monitor -d")
    hl.exec_cmd("xrdb -merge " .. os.getenv("HOME") .. "/.Xresources")
    hl.exec_cmd("hyprctl setcursor elementary 24")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-quickshell start")
    hl.exec_cmd("thunar --daemon")
    hl.exec_cmd("ibus-daemon -drx")
end)
