local mainMod = "SUPER"
local home = os.getenv("HOME") or ""

local function home_path(path)
    return home .. path
end

local function dispatch(command)
    return hl.dsp.exec_cmd("hyprctl dispatch " .. command)
end

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("exo-open --launch TerminalEmulator"), { desc = "[Essential Applications] Terminal" })
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("exo-open --launch TerminalEmulator"), { desc = "[Essential Applications] Terminal (alt)" })
hl.bind("CTRL + Space", hl.dsp.exec_cmd(home_path("/.local/bin/dots-launcher")), { desc = "[Essential Applications] Application launcher" })
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(home_path("/.local/bin/dots-clipboard")), { desc = "[Essential Applications] Clipboard manager" })
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("exo-open --launch FileManager"), { desc = "[Essential Applications] File manager (GUI)" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("kitty --class yazi-popup -e " .. home_path("/.local/bin/dots-yazi") .. " --last-dir"), { desc = "[Essential Applications] File manager (terminal yazi)" })
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("exo-open --launch WebBrowser"), { desc = "[Essential Applications] Web browser" })
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(home_path("/.local/bin/dots-quickshell ipc dashboard toggle")), { desc = "[Essential Applications] Dashboard" })
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(home_path("/.local/bin/dots-power-menu")), { desc = "[Essential Applications] Power menu" })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(home_path("/.local/bin/dots-quickshell ipc lock lock")), { desc = "[Essential Applications] Lock screen" })
hl.bind(mainMod .. " + question", hl.dsp.exec_cmd(home_path("/.local/bin/dots-keyboard-help")), { desc = "[Essential Applications] Keyboard help" })
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd(home_path("/.local/bin/dots-keyboard-help")), { desc = "[Essential Applications] Keyboard help (alt)" })
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(home_path("/.config/hypr/scripts/gaps-interactive.sh")), { desc = "[Essential Applications] Interactive gaps" })

hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close(), { desc = "[Window Management] Close window" })
hl.bind("ALT + Q", hl.dsp.window.close(), { desc = "[Window Management] Close window (alt)" })
hl.bind("ALT + F4", hl.dsp.window.close(), { desc = "[Window Management] Close window (alt F4)" })
hl.bind(mainMod .. " + Space", hl.dsp.window.float({ action = "toggle" }), { desc = "[Window Management] Toggle floating" })
hl.bind(mainMod .. " + M", dispatch("fullscreen 0"), { desc = "[Window Management] Toggle fullscreen" })
hl.bind(mainMod .. " + SHIFT + M", dispatch("fullscreen 1"), { desc = "[Window Management] Toggle maximize" })
hl.bind(mainMod .. " + U", hl.dsp.layout("promote"), { desc = "[Window Management] Promote to column" })
hl.bind(mainMod .. " + apostrophe", hl.dsp.layout("togglefit"), { desc = "[Window Management] Toggle focus fit" })
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd(home_path("/.local/bin/dots-hypr-layout --toggle")), { desc = "[Window Management] Toggle layout profile" })
hl.bind(mainMod .. " + CTRL + SHIFT + W", hl.dsp.exec_cmd(home_path("/.local/bin/dots-hypr-layout --set=scrolling")), { desc = "[Window Management] Force scrolling" })
hl.bind(mainMod .. " + CTRL + ALT + W", hl.dsp.exec_cmd(home_path("/.local/bin/dots-hypr-layout --set=dwindle")), { desc = "[Window Management] Force dwindle" })
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.window.pin(), { desc = "[Window Management] Pin window" })
hl.bind(mainMod .. " + SHIFT + Space", dispatch("focuscurrentorlast"), { desc = "[Window Management] Toggle focus (floating/tiled)" })
hl.bind("ALT + Tab", hl.dsp.exec_cmd(home_path("/.local/bin/dots-snappy-switcher next")), { desc = "[Window Management] Switcher next" })
hl.bind("ALT + SHIFT + Tab", hl.dsp.exec_cmd(home_path("/.local/bin/dots-snappy-switcher prev")), { desc = "[Window Management] Switcher prev" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(home_path("/.config/hypr/scripts/smart-float.sh")), { desc = "[Window Management] Smart float" })
hl.bind(mainMod .. " + CTRL + C", hl.dsp.window.center(), { desc = "[Window Management] Center window" })
hl.bind(mainMod .. " + P", hl.dsp.group.active("f"), { desc = "[Window Management] Focus parent (group)" })
hl.bind(mainMod .. " + C", hl.dsp.group.active("b"), { desc = "[Window Management] Focus child (group)" })

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }), { desc = "[Focus Movement] Left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { desc = "[Focus Movement] Right" })
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }), { desc = "[Focus Movement] Up" })
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }), { desc = "[Focus Movement] Down" })
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }), { desc = "[Focus Movement] Left (vim)" })
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }), { desc = "[Focus Movement] Right (vim)" })
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }), { desc = "[Focus Movement] Up (vim)" })
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }), { desc = "[Focus Movement] Down (vim)" })

hl.bind(mainMod .. " + ALT + H", hl.dsp.layout("move -col"), { desc = "[Scrolling Layout] Viewport left" })
hl.bind(mainMod .. " + ALT + L", hl.dsp.layout("move +col"), { desc = "[Scrolling Layout] Viewport right" })
hl.bind(mainMod .. " + ALT + comma", hl.dsp.layout("swapcol l"), { desc = "[Scrolling Layout] Swap column left" })
hl.bind(mainMod .. " + ALT + period", hl.dsp.layout("swapcol r"), { desc = "[Scrolling Layout] Swap column right" })
hl.bind(mainMod .. " + ALT + minus", hl.dsp.layout("colresize -conf"), { desc = "[Scrolling Layout] Column width -" })
hl.bind(mainMod .. " + ALT + equal", hl.dsp.layout("colresize +conf"), { desc = "[Scrolling Layout] Column width +" })
hl.bind(mainMod .. " + ALT + SHIFT + minus", hl.dsp.layout("colresize -0.05"), { repeating = true, desc = "[Scrolling Layout] Column width fine -" })
hl.bind(mainMod .. " + ALT + SHIFT + equal", hl.dsp.layout("colresize +0.05"), { repeating = true, desc = "[Scrolling Layout] Column width fine +" })
hl.bind(mainMod .. " + ALT + F", hl.dsp.layout("fit active"), { desc = "[Scrolling Layout] Fit active" })
hl.bind(mainMod .. " + ALT + SHIFT + F", hl.dsp.layout("fit visible"), { desc = "[Scrolling Layout] Fit all" })

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }), { desc = "[Window Movement] Move left" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }), { desc = "[Window Movement] Move right" })
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }), { desc = "[Window Movement] Move up" })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }), { desc = "[Window Movement] Move down" })
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }), { desc = "[Window Movement] Move left (vim)" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }), { desc = "[Window Movement] Move right (vim)" })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }), { desc = "[Window Movement] Move up (vim)" })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }), { desc = "[Window Movement] Move down (vim)" })

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"), { desc = "[Window Resizing] Enter resize mode" })
hl.define_submap("resize", function()
    hl.bind("right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
    hl.bind("H", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true, desc = "[Window Resizing] Direct shrink width" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true, desc = "[Window Resizing] Direct grow width" })
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true, desc = "[Window Resizing] Direct shrink height" })
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true, desc = "[Window Resizing] Direct grow height" })
hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true, desc = "[Window Resizing] Direct shrink width (vim)" })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true, desc = "[Window Resizing] Direct grow width (vim)" })
hl.bind(mainMod .. " + CTRL + K", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true, desc = "[Window Resizing] Direct shrink height (vim)" })
hl.bind(mainMod .. " + CTRL + J", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true, desc = "[Window Resizing] Direct grow height (vim)" })

for i = 1, 10 do
    local key = tostring(i % 10)
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }), { desc = "[Workspace Navigation] Switch to " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), { desc = "[Workspace Navigation] Move to " .. i })
    hl.bind(mainMod .. " + CTRL + SHIFT + " .. key, dispatch("movetoworkspacesilent " .. i), { desc = "[Workspace Navigation] Move (silent) to " .. i })
end

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { desc = "[Workspace Navigation] Next workspace" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { desc = "[Workspace Navigation] Previous workspace" })
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }), { desc = "[Workspace Navigation] Cycle forward" })
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }), { desc = "[Workspace Navigation] Cycle backward" })
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"), { desc = "[Workspace Navigation] Toggle scratchpad" })
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }), { desc = "[Workspace Navigation] Move to scratchpad" })

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, desc = "[Mouse Bindings] Move window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, desc = "[Mouse Bindings] Resize window" })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"), { locked = true, repeating = true, desc = "[Media Keys] Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"), { locked = true, repeating = true, desc = "[Media Keys] Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"), { locked = true, desc = "[Media Keys] Mute/unmute" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t"), { locked = true, desc = "[Media Keys] Mic mute/unmute" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, desc = "[Media Keys] Play/pause" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, desc = "[Media Keys] Pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, desc = "[Media Keys] Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, desc = "[Media Keys] Previous track" })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true, desc = "[Media Keys] Stop" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(home_path("/.local/bin/dots brightness '*' + 0.1")), { locked = true, repeating = true, desc = "[Media Keys] Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(home_path("/.local/bin/dots brightness '*' - 0.1")), { locked = true, repeating = true, desc = "[Media Keys] Brightness down" })
hl.bind("SHIFT + XF86MonBrightnessUp", hl.dsp.exec_cmd(home_path("/.local/bin/dots brightness '*' + 0.01")), { locked = true, repeating = true, desc = "[Media Keys] Brightness up (fine)" })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd(home_path("/.local/bin/dots brightness '*' - 0.01")), { locked = true, repeating = true, desc = "[Media Keys] Brightness down (fine)" })

hl.bind("Print", hl.dsp.exec_cmd(home_path("/.local/bin/dots screenshooter")), { desc = "[Screenshots] Full screenshot" })
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(home_path("/.local/bin/dots screenshooter -r")), { desc = "[Screenshots] Area screenshot" })

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"), { desc = "[System Control] Reload Hyprland" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit(), { desc = "[System Control] Exit Hyprland" })
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd(home_path("/.local/bin/dots-quickshell ipc bar toggle")), { desc = "[System Control] Toggle bar" })

hl.bind(mainMod .. " + G", hl.dsp.group.toggle(), { desc = "[Group Management] Toggle group" })
hl.bind(mainMod .. " + period", hl.dsp.group.active("f"), { desc = "[Group Management] Next in group" })
hl.bind(mainMod .. " + comma", hl.dsp.group.active("b"), { desc = "[Group Management] Previous in group" })
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.group.lock_active("toggle"), { desc = "[Group Management] Lock/unlock group" })
