local mainMod = "SUPER"

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("exo-open --launch TerminalEmulator"), { description = "[Essential Applications] Terminal" })
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("exo-open --launch TerminalEmulator"), { description = "[Essential Applications] Terminal (alt)" })
hl.bind("CTRL + Space", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-launcher"), { description = "[Essential Applications] Application launcher" })
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-clipboard"), { description = "[Essential Applications] Clipboard manager" })
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("exo-open --launch FileManager"), { description = "[Essential Applications] File manager (GUI)" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("kitty --class yazi-popup -e " .. os.getenv("HOME") .. "/.local/bin/dots-yazi --last-dir"), { description = "[Essential Applications] File manager (terminal yazi)" })
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("exo-open --launch WebBrowser"), { description = "[Essential Applications] Web browser" })
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-quickshell ipc dashboard toggle"), { description = "[Essential Applications] Dashboard" })
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-power-menu"), { description = "[Essential Applications] Power menu" })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-quickshell ipc lock lock"), { description = "[Essential Applications] Lock screen" })
hl.bind(mainMod .. " + question", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-keyboard-help"), { description = "[Essential Applications] Keyboard help" })
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-keyboard-help"), { description = "[Essential Applications] Keyboard help (alt)" })
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/gaps-interactive.sh"), { description = "[Essential Applications] Interactive gaps" })

hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close(), { description = "[Window Management] Close window" })
hl.bind("ALT + Q", hl.dsp.window.close(), { description = "[Window Management] Close window (alt)" })
hl.bind("ALT + F4", hl.dsp.window.close(), { description = "[Window Management] Close window (alt F4)" })
hl.bind(mainMod .. " + Space", hl.dsp.window.float({ action = "toggle" }), { description = "[Window Management] Toggle floating" })
hl.bind(mainMod .. " + M", function()
    hl.dispatch(hl.dsp.window.fullscreen({ mode = "internal" }))
end, { description = "[Window Management] Toggle fullscreen" })
hl.bind(mainMod .. " + SHIFT + M", function()
    hl.dispatch(hl.dsp.window.fullscreen({ mode = "maximize" }))
end, { description = "[Window Management] Toggle maximize" })
hl.bind(mainMod .. " + U", function()
    hl.dispatch("layoutmsg promote")
end, { description = "[Window Management] Promote to column" })
hl.bind(mainMod .. " + apostrophe", function()
    hl.dispatch("layoutmsg togglefit")
end, { description = "[Window Management] Toggle focus fit" })
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-hypr-layout --toggle"), { description = "[Window Management] Toggle layout profile" })
hl.bind(mainMod .. " + CTRL + SHIFT + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-hypr-layout --set=scrolling"), { description = "[Window Management] Force scrolling" })
hl.bind(mainMod .. " + CTRL + ALT + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-hypr-layout --set=dwindle"), { description = "[Window Management] Force dwindle" })
hl.bind(mainMod .. " + SHIFT + P", function()
    hl.dispatch("pin")
end, { description = "[Window Management] Pin window" })
hl.bind(mainMod .. " + SHIFT + Space", function()
    hl.dispatch("focuscurrentorlast")
end, { description = "[Window Management] Toggle focus (floating/tiled)" })
hl.bind("ALT + Tab", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-snappy-switcher next"), { description = "[Window Management] Switcher next" })
hl.bind("ALT + SHIFT + Tab", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-snappy-switcher prev"), { description = "[Window Management] Switcher prev" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/smart-float.sh"), { description = "[Window Management] Smart float" })
hl.bind(mainMod .. " + CTRL + C", function()
    hl.dispatch("centerwindow")
end, { description = "[Window Management] Center window" })
hl.bind(mainMod .. " + P", function()
    hl.dispatch("changegroupactive f")
end, { description = "[Window Management] Focus parent (group)" })
hl.bind(mainMod .. " + C", function()
    hl.dispatch("changegroupactive b")
end, { description = "[Window Management] Focus child (group)" })

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }), { description = "[Focus Movement] Left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "[Focus Movement] Right" })
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }), { description = "[Focus Movement] Up" })
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }), { description = "[Focus Movement] Down" })
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }), { description = "[Focus Movement] Left (vim)" })
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }), { description = "[Focus Movement] Right (vim)" })
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }), { description = "[Focus Movement] Up (vim)" })
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }), { description = "[Focus Movement] Down (vim)" })

hl.bind(mainMod .. " + ALT + H", function()
    hl.dispatch("layoutmsg move -col")
end, { description = "[Scrolling Layout] Viewport left" })
hl.bind(mainMod .. " + ALT + L", function()
    hl.dispatch("layoutmsg move +col")
end, { description = "[Scrolling Layout] Viewport right" })
hl.bind(mainMod .. " + ALT + comma", function()
    hl.dispatch("layoutmsg swapcol l")
end, { description = "[Scrolling Layout] Swap column left" })
hl.bind(mainMod .. " + ALT + period", function()
    hl.dispatch("layoutmsg swapcol r")
end, { description = "[Scrolling Layout] Swap column right" })
hl.bind(mainMod .. " + ALT + minus", function()
    hl.dispatch("layoutmsg colresize -conf")
end, { description = "[Scrolling Layout] Column width -" })
hl.bind(mainMod .. " + ALT + equal", function()
    hl.dispatch("layoutmsg colresize +conf")
end, { description = "[Scrolling Layout] Column width +" })
hl.bind(mainMod .. " + ALT + SHIFT + minus", function()
    hl.dispatch("layoutmsg colresize -0.05")
end, { repeating = true, description = "[Scrolling Layout] Column width fine -" })
hl.bind(mainMod .. " + ALT + SHIFT + equal", function()
    hl.dispatch("layoutmsg colresize +0.05")
end, { repeating = true, description = "[Scrolling Layout] Column width fine +" })
hl.bind(mainMod .. " + ALT + F", function()
    hl.dispatch("layoutmsg fit active")
end, { description = "[Scrolling Layout] Fit active" })
hl.bind(mainMod .. " + ALT + SHIFT + F", function()
    hl.dispatch("layoutmsg fit visible")
end, { description = "[Scrolling Layout] Fit all" })

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }), { description = "[Window Movement] Move left" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }), { description = "[Window Movement] Move right" })
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }), { description = "[Window Movement] Move up" })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }), { description = "[Window Movement] Move down" })
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }), { description = "[Window Movement] Move left (vim)" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }), { description = "[Window Movement] Move right (vim)" })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }), { description = "[Window Movement] Move up (vim)" })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }), { description = "[Window Movement] Move down (vim)" })

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"), { description = "[Window Resizing] Enter resize mode" })
hl.define_submap("resize", function()
    hl.bind("right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
    hl.bind("H", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true, description = "[Window Resizing] Direct shrink width" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true, description = "[Window Resizing] Direct grow width" })
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true, description = "[Window Resizing] Direct shrink height" })
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true, description = "[Window Resizing] Direct grow height" })
hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true, description = "[Window Resizing] Direct shrink width (vim)" })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true, description = "[Window Resizing] Direct grow width (vim)" })
hl.bind(mainMod .. " + CTRL + K", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true, description = "[Window Resizing] Direct shrink height (vim)" })
hl.bind(mainMod .. " + CTRL + J", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true, description = "[Window Resizing] Direct grow height (vim)" })

for i = 1, 10 do
    local key = tostring(i % 10)
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }), { description = "[Workspace Navigation] Switch to " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), { description = "[Workspace Navigation] Move to " .. i })
    hl.bind(mainMod .. " + CTRL + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), { description = "[Workspace Navigation] Move (silent) to " .. i })
end

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "[Workspace Navigation] Next workspace" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "[Workspace Navigation] Previous workspace" })
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }), { description = "[Workspace Navigation] Cycle forward" })
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }), { description = "[Workspace Navigation] Cycle backward" })
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"), { description = "[Workspace Navigation] Toggle scratchpad" })
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }), { description = "[Workspace Navigation] Move to scratchpad" })

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "[Mouse Bindings] Move window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "[Mouse Bindings] Resize window" })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"), { locked = true, repeating = true, description = "[Media Keys] Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"), { locked = true, repeating = true, description = "[Media Keys] Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"), { locked = true, description = "[Media Keys] Mute/unmute" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t"), { locked = true, description = "[Media Keys] Mic mute/unmute" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "[Media Keys] Play/pause" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "[Media Keys] Pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = "[Media Keys] Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = "[Media Keys] Previous track" })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true, description = "[Media Keys] Stop" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots brightness '*' + 0.1"), { locked = true, repeating = true, description = "[Media Keys] Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots brightness '*' - 0.1"), { locked = true, repeating = true, description = "[Media Keys] Brightness down" })
hl.bind("SHIFT + XF86MonBrightnessUp", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots brightness '*' + 0.01"), { locked = true, repeating = true, description = "[Media Keys] Brightness up (fine)" })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots brightness '*' - 0.01"), { locked = true, repeating = true, description = "[Media Keys] Brightness down (fine)" })

hl.bind("Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots screenshooter"), { description = "[Screenshots] Full screenshot" })
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots screenshooter -r"), { description = "[Screenshots] Area screenshot" })

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"), { description = "[System Control] Reload Hyprland" })
hl.bind(mainMod .. " + SHIFT + E", function()
    hl.dispatch("exit")
end, { description = "[System Control] Exit Hyprland" })
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/dots-quickshell ipc bar toggle"), { description = "[System Control] Toggle bar" })

hl.bind(mainMod .. " + G", function()
    hl.dispatch("togglegroup")
end, { description = "[Group Management] Toggle group" })
hl.bind(mainMod .. " + period", function()
    hl.dispatch("changegroupactive f")
end, { description = "[Group Management] Next in group" })
hl.bind(mainMod .. " + comma", function()
    hl.dispatch("changegroupactive b")
end, { description = "[Group Management] Previous in group" })
hl.bind(mainMod .. " + SHIFT + O", function()
    hl.dispatch("lockactivegroup toggle")
end, { description = "[Group Management] Lock/unlock group" })
