# These are supported funding model platforms

github: ulises-jeremias # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: your-patreon-handle
# open_collective: your-open-collective-handle
# ko_fi: your-ko-fi-handle
# tidelift: npm/babel
# custom:
#   - https://example.com/sponsor
