# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "archlinux/archlinux"

  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '40GB'
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "archlinux-dotfiles"
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    vb.customize ["modifyvm", :id, "--monitorcount", "2"]
    vb.customize ["modifyvm", :id, "--cpus", 4]

    # Customize the amount of memory on the VM:
    vb.memory = "8192"

    vb.customize ['modifyvm', :id, '--clipboard-mode', 'bidirectional']
    vb.customize ["modifyvm", :id, "--vram", "64"]

    unless File.exist?('./data.vdi')
      vb.customize ['createhd', '--filename', './data.vdi', '--variant', 'Fixed', '--size', 20 * 1024]
    end

    vb.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './data.vdi']
  end

  config.vm.provision "VM Setup" type: "shell", path: "provision/vm-setup.sh"
  config.vm.provision "Install Yay", type: "shell", path: "provision/yay.sh"
  config.vm.provision "Bash Conf", type: "file", source: ".bashrc", destination: "/home/vagrant/.bashrc"
  config.vm.provision "Sddm Conf", type: "file", source: "sddm.conf", destination: "/tmp/sddm.conf"
  config.vm.provision "Setup Sddm", type: "shell", path: "provision/sddm.sh"
end
