#!/usr/bin/env bash

## Copyright (C) 2019-2022 Ulises Jeremias Cornejo Fandos
## Licensed under MIT
##
##     @script.name [OPTION] ARGUMENTS...
##
## Options:
##     -h, --help                            Help.
##         --dotfiles-dir=OUTPUT_PATH        Dotfiles output dir, is ~/.local/share/dotfiles by default.
##

set -e

# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
ROOT="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"

NO_CHECK=1
NO_HELP=1
. "${ROOT}"/lib/easy-options/easyoptions.sh
. "${ROOT}"/lib/logs.sh

#==========================================
# Default argument values and preprocessing
#==========================================
time_str=$(date +'%m-%d-%y_%H:%M:%S')
dotfiles_dir=${dotfiles_dir:-"${HOME}/.local/share/dotfiles"}

if ! chezmoi="$(command -v chezmoi)"; then
    bin_dir="${HOME}/.local/bin"
    chezmoi="${bin_dir}/chezmoi"
    echo "Installing chezmoi to '${chezmoi}'" >&2
    if command -v curl >/dev/null; then
      chezmoi_install_script="$(curl -fsSL https://chezmoi.io/get)"
    elif command -v wget >/dev/null; then
      chezmoi_install_script="$(wget -qO- https://chezmoi.io/get)"
    else
      echo "To install chezmoi, you must have curl or wget installed." >&2
      exit 1
    fi
    sh -c "${chezmoi_install_script}" -- -b "${bin_dir}"
    unset chezmoi_install_script bin_dir
fi

if [ ! -d "${dotfiles_dir}" ]; then
    echo "Dotfiles dir '${dotfiles_dir}' does not exist, downloading dotfiles..."
    chezmoi init ulises-jeremias --verbose --apply --source="${dotfiles_dir}"
fi

echo "Running 'chezmoi --source=${dotfiles_dir} $*'" >&2

exec "${chezmoi}" --source="${dotfiles_dir}" "$@"


