#!/usr/bin/env bash

## Copyright (C) 2019-2022 Ulises Jeremias Cornejo Fandos
## Licensed under MIT
##
##     @script.name [OPTION] ARGUMENTS...
##
## Options:
##     -h, --help                            Help.
##         --dotfiles-dir=OUTPUT_PATH        Dotfiles output dir, is ~/.local/share/dotfiles by default.
##

set -e

# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
ROOT="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"

NO_CHECK=1
NO_HELP=1
. "${ROOT}"/lib/easy-options/easyoptions.sh
. "${ROOT}"/lib/logs.sh

#==========================================
# Default argument values and preprocessing
#==========================================
time_str=$(date +'%m-%d-%y_%H:%M:%S')
dotfiles_dir=${dotfiles_dir:-"${HOME}/.local/share/dotfiles"}

if ! chezmoi="$(command -v chezmoi)"; then
    echo "chezmoi is not installed, please install it first."
    exit 1
fi

if [ ! -d "${dotfiles_dir}" ]; then
    echo "Dotfiles dir '${dotfiles_dir}' does not exist, downloading dotfiles..."
    chezmoi init ulises-jeremias --verbose --apply --source="${dotfiles_dir}"
fi

echo "Running 'chezmoi --source=${dotfiles_dir} $*'" >&2

exec "${chezmoi}" --source="${dotfiles_dir}" "$@"


