#!/usr/bin/env bash

ROOT=$(dirname $0)

pkgs=(
    # Needed apps, themes and icons
    arc-gtk-theme
    dbus-python
    dunst
    drun
    feh
    graphicsmagick
    i3lock-fancy
    jgmenu
    jq
    networkmanager-dmenu
    network-manager-applet
    numix-circle-icon-theme
    polybar
    pulseaudio
    rofi
    skippy-xd
    termite
    wmctrl
    zsh
    zsh-syntax-highlighting

    # Needed fonts
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
    noto-fonts-extra
    terminus-font
    ttf-anonymous-pro
    ttf-dejavu
    ttf-fira-code
    ttf-font-awesome
    ttf-liberation
    ttf-linux-libertine

    # xfce4 utils
    exo
    garcon
    libxfce4ui
    libxfce4util
    mousepad
    orage
    ristretto
    thunar
    thunar-archive-plugin
    thunar-media-tags-plugin
    tumbler
    xfburn
    xfce4-artwork
    xfce4-battery-plugin
    xfce4-clipman-plugin
    xfce4-cpufreq-plugin
    xfce4-cpugraph-plugin
    xfce4-datetime-plugin
    xfce4-dev-tools
    xfce4-dict
    xfce4-diskperf-plugin
    xfce4-eyes-plugin
    xfce4-fsguard-plugin
    xfce4-genmon-plugin
    xfce4-mailwatch-plugin
    xfce4-mount-plugin
    xfce4-mpc-plugin
    xfce4-netload-plugin
    xfce4-notes-plugin
    xfce4-notifyd
    xfce4-panel
    xfce4-power-manager
    xfce4-pulseaudio-plugin
    xfce4-screensaver
    xfce4-screenshooter
    xfce4-sensors-plugin
    xfce4-settings
    xfce4-smartbookmark-plugin
    xfce4-systemload-plugin
    xfce4-taskmanager
    xfce4-time-out-plugin
    xfce4-timer-plugin
    xfce4-verve-plugin
    xfce4-wavelan-plugin
    xfce4-weather-plugin
    xfce4-xkb-plugin
    xfconf
    parole
    xfce4-whiskermenu-plugin
)
pkgs=$(printf ",%s" "${pkgs[@]}")
pkgs=${pkgs:1}

$ROOT/scripts/install "$@" --pkgs $pkgs
