#!/usr/bin/env sh

ROOT="$(realpath "$(dirname "$0")")"
PKGNAME=${PKGNAME:-"dots"}

rm -rf "${PKGDIR}/opt/${PKGNAME}" \
    "${PKGDIR}/usr/share/licenses/${PKGNAME}/" \
    "${PKGDIR}/usr/share/doc/${PKGNAME}/"

install -d "${PKGDIR}/opt/${PKGNAME}"

cp -Rf "${ROOT}"/lib "${PKGDIR}/opt/${PKGNAME}"

install -Dm644 "${ROOT}"/LICENSE -t "${PKGDIR}/usr/share/licenses/${PKGNAME}/"
install -Dm644 "${ROOT}"/README.md -t "${PKGDIR}/usr/share/doc/${PKGNAME}/"
