#!/usr/bin/env bash

ROOT=$(dirname $0)

pkgs=(
    # apps
    dunst
    feh
    i3lock-fancy
    jgmenu
    jq
    networkmanager-dmenu
    polybar
    pulseaudio
    rofi
    skippy-xd
    termite
    zsh
    # config
    zsh-syntax-highlighting
    numix-circle-icon-theme
    wmctrl
    # fonts
    noto-fonts
    noto-fonts-extra
    terminus-font
    ttf-anonymous-pro
    ttf-dejavu
    ttf-fira-code
    ttf-liberation
    ttf-linux-libertine
    # tools
    dbus-python
    drun
    graphicsmagick
    network-manager-applet
    picom
    # utils
    mousepad
    xfce4-about
    xfce4-diskperf-plugin
    xfce4-datetime-plugin
    xfce4-popup-applicationsmenu
    xfce4-power-manager
    xfce4-accessibility
    xfce4-popup-directorymenu
    xfce4-appearance
    xfce4-xkb-plugin
    xfce4-eyes-plugin
    xfce4-panel
    xfce4-popup-windowmenu
    xfce4-manager
    xfce4-kiosk-query
    xfce4-pm-helper
    xfce4-power-manager
)
pkgs=$(printf ",%s" "${pkgs[@]}")
pkgs=${pkgs:1}

$ROOT/scripts/install "$@" --pkgs $pkgs
