Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.provision :shell, :path => "provision.core.sh"
  config.vm.provision :shell, :path => "provision.aur.sh", :privileged => false
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "10240"
    # Enable sound support
    # (available options for audiocontroller: "hda" for Linux host, "sb16", "ac97" for Windows host)
    # (available options for audio: "alsa" or "pulse" for Linux host, "dsound" for Windows host, "coreaudio" for Mac OS)
    # vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'ac97']
    # Customize video memory
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end
end
