[".config/alacritty/themes"]
    type = "archive"
    url = "https://github.com/alacritty/alacritty-theme/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    path = "themes"
    include = ["**/themes/**"]
[".config/rofi/themes"]
    type = "archive"
    url = "https://github.com/ulises-jeremias/rofi-themes/archive/main.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    path = "themes"
    include = ["**/themes/**"]
[".zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"]
    type = "file"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/zsh-syntax-highlighting.zsh?raw=true"
    exact = true
    refreshPeriod = "168h"
[".zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"]
    type = "file"
    url = "https://github.com/zsh-users/zsh-autosuggestions/blob/master/zsh-autosuggestions.zsh?raw=true"
    exact = true
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    refreshPeriod = "168h"
    path = "tpm"
    stripComponents = 1
