#!/usr/bin/env zsh

#===================================================================================
#  DESCRIPTION:  You realize, Dr. Angelo, that my intelligence has surpassed yours.
#       AUTHOR:  Jarrod Taylor
#       UPDATED: Ulises Jeremias Cornejo Fandos
#
#                 .__
#  ________  _____|  |_________   ____
#  \___   / /  ___/  |  \_  __ \_/ ___\
#   /    /  \___ \|   Y  \  | \/\  \___
#  /_____ \/____  >___|  /__|    \___  >
#        \/     \/     \/            \/
#
#===================================================================================
#

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source the prompt and aliases
#-------------------------------------------------------------------------------
if [[ -z "${ZSHRUN}" ]]; then
    [[ -f ~/.zsh_prompt ]] && source ~/.zsh_prompt
    [[ -f ~/.zsh_aliases ]] && source ~/.zsh_aliases
fi

# General Settings
# Autoload tab completion
#-------------------------------------------------------------------------------
autoload -U compinit
compinit -C

#
# Modify default zsh directory coloring on ls commands
#-------------------------------------------------------------------------------
export LSCOLORS=gxfxcxdxbxegedabagacad

#
# Completion settings
#-------------------------------------------------------------------------------
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "$LS_COLORS"
zstyle -e ':completion:*:(ssh|scp|sshfs|ping|telnet|nc|rsync):*' hosts '
        reply=( ${=${${(M)${(f)"$(<~/.ssh/config)"}:#Host*}#Host }:#*\**} )'

#
# Set the desired setup options man zshoptions
#-------------------------------------------------------------------------------
# If command can't be executed, and command is name of a directory, cd to directory
setopt auto_cd
# Make cd push the old directory onto the directory stack.
setopt auto_pushd
# Safety for overwriting files use >| instead of > to over write files
setopt noclobber
# Prevents aliases on the command line from being internally substituted before
# completion is attempted. The effect is to make the alias a distinct command
# for completion purposes.
setopt complete_aliases
# Treat the #, ~ and ^ characters as part of patterns for filename
# generation, etc.  (An initial unquoted `~' always produces named directory
# expansion.)
setopt extended_glob
# If a new command line being added to the history list duplicates an older one,
# the older command is removed from the list (even if it is not the previous event).
setopt hist_ignore_all_dups
#  Remove command lines from the history list when the first character on the line
#  is a space, or when one of the expanded aliases contains a leading space.
setopt hist_ignore_space
# This  option  both  imports new commands from the history file, and also
# causes your typed commands to be appended to the history file
setopt share_history
setopt noflowcontrol
# When listing files that are possible completions, show the type of each file
# with a trailing identifying mark.
setopt list_types
# Append a trailing / to all directory names resulting from filename
# generation (globbing).
setopt mark_dirs
# Perform a path search even on command names with slashes in them.
# Thus if /usr/local/bin is in the user's path, and he or she types
# X11/xinit, the  command /usr/local/bin/X11/xinit will be executed
# (assuming it exists).
setopt path_dirs
# If set, `%' is treated specially in prompt expansion.
setopt prompt_percent
# If set, parameter expansion, command substitution and arithmetic
# expansion are performed in prompts.
# Substitutions within prompts do not affect the command status.
setopt prompt_subst

#
# History settings
#-------------------------------------------------------------------------------
HISTFILE=~/.zsh_history
HISTFILESIZE=65536 # search this with `grep | sort -u`
HISTSIZE=4096
SAVEHIST=4096
REPORTTIME=60 # Report time statistics for progs that take more than a minute to run

#
# utf-8 in the terminal, will break stuff if your term isn't utf aware
#-------------------------------------------------------------------------------
export LANG=en_US.UTF-8
export LC_ALL=$LANG
export LC_COLLATE=C

#
# Use the correct ctags
#-------------------------------------------------------------------------------
#
# Editor and display configurations
#-------------------------------------------------------------------------------
export BROWSER=xdg-open
export EDITOR='nvim'
export VISUAL='nvim'
export GIT_EDITOR=$EDITOR
export LESS='-imJMWR'
export PAGER="less $LESS"
export MANPAGER=$PAGER
export GIT_PAGER=$PAGER

# Eliminate lag between transition from normal/insert mode
#-------------------------------------------------------------------------------
# If this causes issue with other shell commands it can be raised default is 4
export KEYTIMEOUT=1

(wal -R -q -e -t -n) >> /dev/null

# Source Custom Configurations
# if there are files in ~/.zsh/config.d/*.zsh, source them
if [ -d ~/.zsh/config.d ]; then
    for config_file ($HOME/.zsh/config.d/*.zsh(N)); do
        source $config_file
    done
fi
