#!/usr/bin/env bash

if [ ! -f "$HOME/.xsync" ] && (($(xrandr -q | grep -c -w connected) == 1)); then
    mon=$(xrandr -q | grep -w connected | awk '{print $1}')
    res_x=$(xrandr | sed "s/x/\ /g" | grep \* | awk '{print $1}')
    res_y=$(xrandr | sed "s/x/\ /g" | grep \* | awk '{print $2}')
    if ((res_x < 1920)); then
        scale_x=$(bc -l <<<"1920/$res_x")
        scale_y=$(bc -l <<<"1080/$res_y")
        xrandr --output "${mon}" --scale "${scale_x}x${scale_y}"
    else
        xrandr --auto
    fi
elif [ -f "$HOME/.xsync" ]; then
    if ! "$HOME"/.xsync; then xrandr --auto; fi
else
    xrandr --auto
fi

# run polkit-gnome-authentication-agent-1 in the background
[[ -f /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]] && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# run xfsettingsd in the background, required for xfce settings to work
xfsettingsd &

# run xfce4-power-manager in the background
xfce4-power-manager --daemon &

# load picom
picom --config ~/.config/picom/picom.conf --daemon &

# restore colorscheme
wal -R -q

# start eww daemon
eww daemon

# run feh-blur in the background
# dots feh-blur --blur 32 --darken 12 -c --no-animate -d

# start nm-applet
nm-applet &

# start greenclip daemon
greenclip daemon &

# start thunar daemon
thunar --daemon &
