#!/usr/bin/env bash

XDG_CONFIG_HOME="${HOME}"/.config
export XDG_CONFIG_HOME

[[ "${PATH}" == *"${HOME}/.local/bin"* ]] || export PATH="${HOME}/.local/bin:${PATH}"

# Add pyenv shims to PATH if pyenv is installed and shims exist and it's not already in the PATH
if [[ -d "${HOME}/.pyenv/shims" && ":$PATH:" != *":$HOME/.pyenv/shims:"* ]]; then
    export PATH="${HOME}/.pyenv/shims:${PATH}"
fi
