#!/usr/bin/env bash

ROOT=$(dirname "$0")

sudo rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/alacritty/alacritty.yml > /dev/null 2>&1
mkdir "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/alacritty > /dev/null 2>&1
ln -sf "${ROOT}"/alacritty.yml "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/alacritty/alacritty.yml
