#!/usr/bin/env bash

ROOT=$(dirname "$0")

sudo rm -rf "${XDG_CONFIG_HOME}"/polybar/modules > /dev/null 2>&1
sudo rm -rf "${XDG_CONFIG_HOME}"/polybar/polybars > /dev/null 2>&1
sudo rm -rf "${XDG_CONFIG_HOME}"/polybar/config > /dev/null 2>&1
sudo rm -rf "${XDG_CONFIG_HOME}"/polybar/launch > /dev/null 2>&1
sudo rm -rf "${XDG_CONFIG_HOME}"/polybar/master.conf > /dev/null 2>&1
sudo rm -rf "${XDG_CONFIG_HOME}"/polybar/modules.conf > /dev/null 2>&1

mkdir "${XDG_CONFIG_HOME}"/polybar > /dev/null 2>&1

ln -sf "${ROOT}"/modules "${XDG_CONFIG_HOME}"/polybar/modules
ln -sf "${ROOT}"/polybars "${XDG_CONFIG_HOME}"/polybar/polybars
ln -sf "${ROOT}"/config "${XDG_CONFIG_HOME}"/polybar/config
ln -sf "${ROOT}"/launch "${XDG_CONFIG_HOME}"/polybar/launch
ln -sf "${ROOT}"/master.conf "${XDG_CONFIG_HOME}"/polybar/master.conf
ln -sf "${ROOT}"/modules.conf "${XDG_CONFIG_HOME}"/polybar/modules.conf
