#!/usr/bin/env bash

ROOT=$(dirname $0)

sudo rm -rf ~/.config/polybar/modules > /dev/null 2>&1
sudo rm -rf ~/.config/polybar/polybars > /dev/null 2>&1
sudo rm -rf ~/.config/polybar/config > /dev/null 2>&1
sudo rm -rf ~/.config/polybar/launch > /dev/null 2>&1
sudo rm -rf ~/.config/polybar/master.conf > /dev/null 2>&1
sudo rm -rf ~/.config/polybar/modules.conf > /dev/null 2>&1

mkdir ~/.config/polybar > /dev/null 2>&1

ln -sf "${ROOT}"/modules ~/.config/polybar/modules
ln -sf "${ROOT}"/polybars ~/.config/polybar/polybars
ln -sf "${ROOT}"/config ~/.config/polybar/config
ln -sf "${ROOT}"/launch ~/.config/polybar/launch
ln -sf "${ROOT}"/master.conf ~/.config/polybar/master.conf
ln -sf "${ROOT}"/modules.conf ~/.config/polybar/modules.conf
