#!/usr/bin/env sh

# Terminate already running bar instances
pkill -9 polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

themes=(
    "top-bar-only"
    "small-top-bar-only"
    "two-bars-small-layout"
    "two-bars-layout"
)

source ~/.config/polybar/.polybar-session
SESSION="$POLYBAR_SESSION"

echo $SESSION
if [[ " ${themes[@]} " =~ " $1 " ]]; then
    SESSION="$1"
fi


if [ "$SESSION" = "top-bar-only" ]; then
    polybar polybar-top-only -r
elif [ "$SESSION" = "small-top-bar-only" ]; then
    polybar small-polybar-top-only -r
elif [ "$SESSION" = "two-bars-small-layout" ]; then
    polybar small-polybar-top -r &
    polybar small-polybar-bottom -r
else
    polybar polybar-top -r &
    polybar polybar-bottom -r
fi
