#!/usr/bin/env sh

# Terminate already running bar instances
pkill -9 polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

polybars=$(xgetres polybar.polybars)
polybars="${polybars:-polybar-top,polybar-bottom}"

for bar in $(echo ${polybars} | tr ',' '\n'); do
    polybar ${bar} -r &
done
