# shellcheck shell=bash
# dots-scripts.sh - Registry of available dots scripts
# This file is sourced by dots and dots-scripts commands

scripts_list=(
  "💾 backup: Create, list, and rollback dotfiles backups with cron scheduling support"
  "🔋 battery-monitor: Battery monitoring daemon with threshold notifications"
  "💡 brightness: Control screen brightness using xbacklight, brightnessctl, blight, or xrandr"
  "🌐 check-network: Check network connectivity status"
  "📦 checkupdates: Check for available system package updates"
  "📋 clipboard: Unified clipboard manager (quickshell > copyq > cliphist > minimal)"
  "🎛️ appearance: Unified appearance manager (list/current/apply/variant/mode/wallpaper/sync)"
  "⚙️ config-manager: Manage configuration snapshots and backups"
  "🎯 default-apps: Configure XDG default applications using handlr"
  "📋 dependencies: Check and install required system dependencies"
  "📁 file-manager: Launch XDG default file manager"
  "📨 git-notify: Send notifications when git commits are made"
  "🎨 gtk-theme: Intelligent GTK theme management with rice integration and auto-detection"
  "🖥️ hypr-monitors: Manage Hyprland monitor configurations and layouts"
  "🖼️ hyprpaper-set: Set wallpapers on Wayland with hyprpaper"
  "📋 jgmenu: Launch jgmenu application launcher with smart positioning"
  "🔠 keyboard-help: Interactive keyboard shortcuts help overlay for Hyprland"
  "⌨️ keyboard-layout: Toggle keyboard layouts for Hyprland/Wayland/X11"
  "⚙️ keyboard-settings: Open LXQt keyboard configuration GUI"
  "🚀 launcher: Unified application launcher (quickshell > fuzzel > wofi > minimal)"
  "🔒 lockscreen: Wayland lockscreen with hyprlock (betterlockscreen alternative)"
  "🎤 microphone: Monitor and toggle microphone mute status with visual indicators"
  "🔄 next-workspace: Switch to the next existing Hyprland workspace"
  "🌙 night-mode: Toggle night mode/blue light filter"
  "⚡ performance: Monitor system performance and run benchmarks"
  "🎚️ performance-mode: Select CPU performance profiles (auto-cpufreq)"
  "🔌 power-menu: System power menu (quickshell session menu)"
  "📁 yazi: Launch yazi with smart defaults, preview diagnostics, and last-dir support"
  "🌾 rice: Legacy-compatible alias for appearance themes/rices"
  "📸 screenshooter: Take screenshots with various options and formats"
  "📜 scripts: Interactive menu to browse and launch available dots scripts"
  "🔐 security-audit: Run comprehensive security audits and apply security fixes"
  "⚙️ settings-gui: Central configuration hub with unified access to system settings"
  "🎨 smart-colors: Analyze color palettes and generate M3/semantic colors"
  "⚡ snappy-switcher: Animated Alt+Tab window switcher with rice theme integration"
  "⬆️ sysupdate: Perform comprehensive system updates"
  "🎨 theme-selector: GTK theme selector (nwg-look > fuzzel > wofi)"
  "🔄 toggle: Toggle state of Quickshell components, compositor, and notifications"
  "🔔 updates: Check and display available package updates with notifications"
  "🎨 wal-reload: Reload pywal colorscheme and apply M3 smart colors to Quickshell, Hyprland, Kitty"
  "🐚 quickshell: Quickshell desktop shell management (start, stop, restart, status, IPC, presets, config)"
  "🌤️ weather-info: Display current weather information and forecasts"
)
