# shellcheck shell=bash
# dots-scripts.sh - Registry of available dots scripts
# This file is sourced by dots command

scripts_list=(
	"💾 backup: RETIRED — use: horneroctl backup list|schedule|create|restore [--yes]"
	"🔋 battery-monitor: RETIRED — use: horneroctl hardware battery monitor [--low=N --crit=N --interval=S --daemon]"
	"💡 brightness: RETIRED — use: horneroctl hardware brightness status|set|up|down [--display NAME]"
	"🌐 check-network: RETIRED — use: horneroctl hardware network status [--timeout=N]"
	"📦 checkupdates: RETIRED — use: horneroctl package check (falls back to pacman-contrib checkupdates)"
	"🎨 color-scheme: RETIRED — use: horneroctl appearance scheme regenerate|sync-state|set-mode|set-variant [--yes]"
	"📋 clipboard: RETIRED — use: horneroctl capture clipboard [--backend NAME]"
	"🎛️ appearance: RETIRED — use: horneroctl appearance theme|gtk|colors|scheme …"
	"⚙️ config-manager: RETIRED — use: horneroctl config snapshot create|list|restore [--yes]"
	"🎯 default-apps: RETIRED — use: horneroctl config default-apps list|set <mime> <app> [--yes]"
	"📋 dependencies: RETIRED — use: horneroctl package deps [--install]"
	"📁 file-manager: RETIRED — use: horneroctl apps files [--path PATH]"
	"📨 git-notify: RETIRED — use: horneroctl apps git-status"
	"🎨 gtk-theme: RETIRED — use: horneroctl appearance gtk …"
	"🎨 accent-override: RETIRED — use: horneroctl appearance accent show|set|clear [--yes]"
	"🧭 hypr-layout: RETIRED — use: horneroctl hypr layout current|status|set|toggle|restore [--yes]"
	"✨ hypr-animations: RETIRED — use: horneroctl hypr animations list|current|set|next|restore [--yes]"
	"🖥️ hypr-monitors: RETIRED — use: horneroctl hypr monitors list|status|set [--yes]"
	"🧩 hyprland-plugins: RETIRED — use: horneroctl hypr plugins list|status|install [--yes]"
	"🎨 hyprlock-theme: RETIRED — use: horneroctl appearance hyprlock --yes"
	"🔠 keyboard-help: RETIRED — use: horneroctl hardware keyboard keys"
	"⌨️ keyboard-layout: RETIRED — use: horneroctl hardware keyboard layout [--yes] (toggle); --get|--current (reads)"
	"⚙️ keyboard-settings: RETIRED — use: horneroctl hardware keyboard settings"
	"🚀 launcher: RETIRED — use: horneroctl apps launch"
	"🔒 lockscreen: RETIRED — use: horneroctl power lock --yes"
	"🎤 microphone: RETIRED — toggle: horneroctl hardware mic toggle --yes (event listen loop removed, no callers)"
	"🎨 m3-colors: RETIRED — use: horneroctl appearance colors m3 --yes"
	"🔄 next-workspace: RETIRED — use: horneroctl hypr workspace next|prev --yes"
	"🌙 night-mode: RETIRED — use: horneroctl appearance night-mode status|toggle [--yes]"
	"⚡ performance: RETIRED — use: horneroctl apps performance startup|memory|benchmark|report|mode"
	"🎚️ performance-mode: RETIRED — use: horneroctl apps performance mode [set <profile>] [--yes]"
	"🔌 power-menu: RETIRED — use: horneroctl shell ipc -- call drawers toggle session"
	"📁 yazi: RETIRED — use: horneroctl apps terminal-file [--last-dir]"
	"📸 screenshooter: RETIRED — use: horneroctl capture screenshot [--fullscreen|--region --yes]"
	"🔐 security-audit: RETIRED — use: horneroctl apps audit [--permissions|--secrets|--system] [--fix|--report|--json] [--yes]"
	"⚙️ settings-gui: Central configuration hub with unified access to system settings"
	"🎨 smart-colors: RETIRED — use: horneroctl appearance colors generate|status [--yes]"
	"⚡ snappy-switcher: Animated Alt+Tab window switcher with appearance theme integration"
	"🎨 theme-selector: RETIRED — use: horneroctl config gui --pane appearance"
	"🔄 toggle: RETIRED — use: horneroctl apps toggle <component> --yes"
	"🔔 updates: RETIRED — count readout: horneroctl package updates (polybar loop removed, no callers)"
	"⬆️ sysupdate: RETIRED (no script ever shipped) — use: horneroctl package upgrade --yes"
	"🎨 wal-reload: RETIRED — use: horneroctl wallpaper reload --yes"
	"🖼️ wallpaper-set: RETIRED — use: horneroctl wallpaper set <path> --yes"
	"🖼️ wallpaper-current: RETIRED — use: horneroctl wallpaper current"
	"🐚 quickshell: RETIRED — use: horneroctl shell status|start|stop|restart|preset …"
	"🎥 recorder: RETIRED — use: horneroctl capture record start|stop|pause [--region --sound --sr --fps N --yes]"
	"🌤️ weather-info: RETIRED — use: horneroctl apps weather <--getdata|--icon|--temp|--hex|--stat|--loc|--quote|--quote2>"
)
