"""
HorneroConfig — Smart Colorscheme for Ranger

This colorscheme auto-adapts to your current rice by reading colors from
~/.cache/dots/smart-colors/colors-ranger.py (generated by dots-smart-colors).

If the generated colors file doesn't exist, it falls back to a clean theme
that reads from ~/.cache/wal/colors (pywal) or uses sensible defaults.

The result: ranger's appearance automatically matches your wallpaper and rice.
"""

import os
import ranger.gui.color as style
from ranger.gui.colorscheme import ColorScheme

# ─── Color Loading ──────────────────────────────────────────────────────────

def _hex_to_term256(hex_color):
    """Convert a hex color (#RRGGBB) to the nearest xterm-256 color index."""
    if not hex_color or not hex_color.startswith('#') or len(hex_color) != 7:
        return -1
    try:
        r = int(hex_color[1:3], 16)
        g = int(hex_color[3:5], 16)
        b = int(hex_color[5:7], 16)
    except ValueError:
        return -1

    # Check if it's a grayscale color
    if r == g == b:
        if r < 8:
            return 16
        if r > 248:
            return 231
        return round((r - 8) / 247 * 24) + 232

    # Map to 6x6x6 color cube (indices 16-231)
    ri = round(r / 255 * 5)
    gi = round(g / 255 * 5)
    bi = round(b / 255 * 5)
    return 16 + (36 * ri) + (6 * gi) + bi


def _load_colors():
    """Load colors from smart-colors or pywal cache."""
    colors = {}

    # Priority 1: Smart colors generated for ranger
    ranger_colors = os.path.expanduser("~/.cache/dots/smart-colors/colors-ranger.py")
    if os.path.exists(ranger_colors):
        try:
            with open(ranger_colors) as f:
                exec(f.read(), colors)
            return colors
        except Exception:
            pass

    # Priority 2: Shell colors from smart-colors
    shell_colors = os.path.expanduser("~/.cache/dots/smart-colors/colors.sh")
    if os.path.exists(shell_colors):
        try:
            with open(shell_colors) as f:
                for line in f:
                    line = line.strip()
                    if line.startswith('export ') or line.startswith('#') or not line:
                        continue
                    if '=' in line:
                        key, _, val = line.partition('=')
                        key = key.replace('export ', '').strip()
                        val = val.strip().strip("'\"")
                        colors[key] = val
            return colors
        except Exception:
            pass

    # Priority 3: Pywal colors
    wal_colors = os.path.expanduser("~/.cache/wal/colors")
    if os.path.exists(wal_colors):
        try:
            with open(wal_colors) as f:
                for i, line in enumerate(f):
                    colors[f'color{i}'] = line.strip()
            return colors
        except Exception:
            pass

    return colors


# Load colors once at import time
_COLORS = _load_colors()


def _get_color(key, fallback_color):
    """Get a terminal color index from loaded colors, with fallback."""
    hex_val = _COLORS.get(key)
    if hex_val and isinstance(hex_val, str) and hex_val.startswith('#'):
        result = _hex_to_term256(hex_val)
        if result >= 0:
            return result
    # If the value is already an int (from colors-ranger.py), use it directly
    if hex_val and isinstance(hex_val, int):
        return hex_val
    return fallback_color


# ─── Semantic Color Mapping ─────────────────────────────────────────────────

# Map semantic concepts to loaded colors, with sensible fallbacks
BG = _get_color('background', style.default)
FG = _get_color('foreground', style.default)
BG_ALT = _get_color('background_alt', 236)

ACCENT = _get_color('accent', style.cyan)
ERROR = _get_color('error', style.red)
WARNING = _get_color('warning', style.yellow)
SUCCESS = _get_color('success', style.green)
INFO = _get_color('info', style.blue)

# Base16 palette
COLOR0 = _get_color('color0', style.black)
COLOR1 = _get_color('color1', style.red)
COLOR2 = _get_color('color2', style.green)
COLOR3 = _get_color('color3', style.yellow)
COLOR4 = _get_color('color4', style.blue)
COLOR5 = _get_color('color5', style.magenta)
COLOR6 = _get_color('color6', style.cyan)
COLOR7 = _get_color('color7', style.white)


class Scheme(ColorScheme):
    """Smart adaptive colorscheme that follows your rice."""

    progress_bar_color = ACCENT

    def use(self, context):
        fg, bg, attr = style.default_colors

        # ── Main File Browser ────────────────────────────────────────────
        if context.reset:
            return style.default_colors

        elif context.in_browser:
            # Directories
            if context.selected:
                attr = style.reverse
            if context.empty or context.error:
                fg = ERROR
                bg = style.default
            if context.border:
                fg = COLOR4
            if context.image:
                fg = COLOR5
            if context.video or context.audio:
                fg = COLOR5
                attr |= style.bold
            if context.document:
                fg = COLOR3
            if context.container:
                fg = COLOR1
                attr |= style.bold
            if context.directory:
                fg = COLOR4
                attr |= style.bold
            elif context.executable and not any(
                (context.media, context.container, context.fifo, context.socket)
            ):
                fg = COLOR2
                attr |= style.bold
            if context.socket:
                fg = COLOR5
                attr |= style.bold
            if context.fifo or context.device:
                fg = COLOR3
                if context.device:
                    attr |= style.bold
            if context.link:
                fg = COLOR6 if context.good else COLOR1
            if context.tag_marker and not context.selected:
                attr |= style.bold
                if fg in (COLOR1, COLOR5):
                    fg = style.white
                else:
                    fg = COLOR1
            if not context.selected and (context.cut or context.copied):
                fg = COLOR0
                attr |= style.bold
            if context.main_column:
                if context.selected:
                    attr |= style.bold
                if context.marked:
                    attr |= style.bold
                    fg = WARNING
            if context.badinfo:
                if attr & style.reverse:
                    bg = ERROR
                else:
                    fg = ERROR

            if context.inactive_pane:
                fg = COLOR6

            # VCS (git) integration colors
            if context.vcsinfo:
                fg = INFO
                attr &= ~style.bold
            if context.vcscommit:
                fg = COLOR3
                attr &= ~style.bold
            if context.vcsdate:
                fg = COLOR6
                attr &= ~style.bold

            if context.vcsconflict:
                fg = ERROR
                attr |= style.bold
            if context.vcschanged:
                fg = WARNING
                attr |= style.bold
            if context.vcsunknown:
                fg = COLOR1
            if context.vcsstaged:
                fg = SUCCESS
            if context.vcssync:
                fg = COLOR2
            if context.vcsignored:
                fg = style.default
            if context.vcsremote and not context.vcssync:
                fg = COLOR1

        # ── Title Bar ────────────────────────────────────────────────────
        elif context.in_titlebar:
            attr |= style.bold
            if context.hostname:
                fg = COLOR1 if context.bad else COLOR2
            elif context.directory:
                fg = ACCENT
            elif context.tab:
                if context.good:
                    bg = ACCENT
                    fg = COLOR0
            elif context.link:
                fg = COLOR6

        # ── Status Bar ───────────────────────────────────────────────────
        elif context.in_statusbar:
            if context.permissions:
                if context.good:
                    fg = COLOR2
                elif context.bad:
                    fg = COLOR1
            if context.marked:
                attr |= style.bold | style.reverse
                fg = WARNING
            if context.frozen:
                attr |= style.bold | style.reverse
                fg = COLOR6
            if context.message:
                if context.bad:
                    attr |= style.bold
                    fg = ERROR
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = INFO
                attr &= ~style.bold
            if context.vcscommit:
                fg = COLOR3
                attr &= ~style.bold

        # ── Task View ────────────────────────────────────────────────────
        if context.in_taskview:
            if context.title:
                fg = COLOR4
            if context.selected:
                attr |= style.reverse
            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        return fg, bg, attr
