#!/usr/bin/env bash

pkg_install() {
  if [ -f "${ROOT}/debian/$1" ]; then
    bash "${ROOT}"/debian/"$1"
    return $?
  fi
  sudo apt install "$1" -y
  return $?
}

pkg_exists() {
  [ -f "${ROOT}/debian/$1" ] || apt search "$1"
  return $?
}

update_db() {
  sudo apt update
  return $?
}
