#!/usr/bin/env bash

git clone https://github.com/firecat53/networkmanager-dmenu /tmp/networkmanager-dmenu
[ ! -d ~/bin ] && mkdir ~/bin
cp /tmp/networkmanager-dmenu/networkmanager_dmenu ~/bin
chmod +x ~/bin/networkmanager_dmenu
