#!/usr/bin/env bash

ROOT=$(dirname "$0")

sudo rm -rf "${XDG_CONFIG_HOME}"/fontconfig/fonts.conf > /dev/null 2>&1

mkdir "${XDG_CONFIG_HOME}"/fontconfig > /dev/null 2>&1

ln -sf "${ROOT}"/fonts.conf "${XDG_CONFIG_HOME}"/fontconfig/fonts.conf
