services:
  xephyr:
    build:
      context: .
      dockerfile: xephyr.Dockerfile
    command: Xephyr :1225 -ac -br -screen 1024x768 -resizeable -reset -terminate
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "1225:1225"
    networks:
      - dots
  dots:
    build:
      context: ${OS:-arch-linux}
      dockerfile: Dockerfile
      args:
        - WINDOW_MANAGER=${WINDOW_MANAGER:-i3}
    depends_on:
      - xephyr
    environment:
      - DISPLAY=:1225
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../..:/home/dots/dotfiles-repo:ro
    networks:
      - dots

networks:
  dots:
