#!/usr/bin/env bash

player_status=$(playerctl status 2>/dev/null)

# Early return if status is not Playing or Paused
if [ "${player_status}" != "Playing" ] && [ "${player_status}" != "Paused" ]; then
  echo ""
  exit 0
fi

title="$(playerctl metadata -s --format '{{trunc(title, 30)}}' | awk 'NR==1 {print; exit}')"

status_label=""
if [ "${player_status}" = "Playing" ]; then
  status_label="%{F#ebcb8b}󰏥%{F}"
elif [ "${player_status}" = "Paused" ]; then
  status_label="%{F#a3be8c}󰐌%{F}"
fi

# Set the labels for the buttons
prev_label="%{T4}%{A1:playerctl prev:}%{F#b48ead}󰒮%{F}%{A}%{T-}"
play_pause_label="%{T5}%{A1:playerctl play-pause:}${status_label}%{A}%{T-}"
next_label="%{T4}%{A1:playerctl next:}%{F#b48ead}󰒭%{F}%{A}%{T-}"

echo "${prev_label} ${play_pause_label} ${next_label} %{T1}%{F#b48ead}${title}%{F}%{T-}"
