#!/usr/bin/env bash

ROOT=$(dirname "$0")

rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu/jgmenurc > /dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu/append.csv > /dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu/prepend.csv > /dev/null 2>&1

mkdir "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu > /dev/null 2>&1

ln -sf "${ROOT}"/jgmenurc "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu/jgmenurc
ln -sf "${ROOT}"/append.csv "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu/append.csv
ln -sf "${ROOT}"/prepend.csv "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/jgmenu/prepend.csv
