#!/usr/bin/env bash

ROOT=$(dirname "$0")

SOURCE_DIR=$(realpath "${ROOT}")
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}"/.config}"

rm -rf "${XDG_CONFIG_HOME}"/jgmenu/jgmenurc > /dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME}"/jgmenu/append.csv > /dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME}"/jgmenu/prepend.csv > /dev/null 2>&1

mkdir "${XDG_CONFIG_HOME}"/jgmenu > /dev/null 2>&1

ln -sf "${SOURCE_DIR}"/jgmenurc "${XDG_CONFIG_HOME}"/jgmenu/jgmenurc
ln -sf "${SOURCE_DIR}"/append.csv "${XDG_CONFIG_HOME}"/jgmenu/append.csv
ln -sf "${SOURCE_DIR}"/prepend.csv "${XDG_CONFIG_HOME}"/jgmenu/prepend.csv
