#!/usr/bin/env bash

ROOT=$(dirname "$0")

SOURCE_DIR=$(realpath "${ROOT}")
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}"/.config}"

rm -rf "${XDG_CONFIG_HOME}"/dunst/dunstrc > /dev/null 2>&1
mkdir "${XDG_CONFIG_HOME}"/dunst > /dev/null 2>&1
ln -sf "${SOURCE_DIR}"/dunstrc "${XDG_CONFIG_HOME}"/dunst/dunstrc
