#!/usr/bin/env bash

ROOT=$(dirname "$0")

sudo rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/dunst/dunstrc > /dev/null 2>&1

mkdir "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/dunst > /dev/null 2>&1

ln -sf "${ROOT}"/dunstrc "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/dunst/dunstrc
