#!/usr/bin/env bash

ROOT=$(dirname "$0")

sudo rm -rf ~/.config/feh/.fehbg > /dev/null 2>&1

mkdir ~/.config/feh > /dev/null 2>&1

ln -sf "${ROOT}"/fehbg ~/.config/feh/.fehbg
[ ! -f ~/.config/feh/wallpaper.jpg ] && ln -sf "${ROOT}"/wallpaper.jpg ~/.config/feh/wallpaper.jpg
