#!/usr/bin/env bash

SOURCE_DIR="$(realpath "$(dirname "$0")")"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}"/.config}"

rm -rf "${XDG_CONFIG_HOME}"/wpg/wpg.conf > /dev/null 2>&1
mkdir "${XDG_CONFIG_HOME}"/wpg > /dev/null 2>&1
ln -sf "${SOURCE_DIR}"/wpg.conf "${XDG_CONFIG_HOME}"/wpg/wpg.conf
