#!/usr/bin/env bash

SOURCE_DIR="$(realpath "$(dirname "$0")")"
DOTFILES_DIR=$(realpath "${SOURCE_DIR}/..")

create_symlink() {
  to=${2:-"$HOME/.$1"}

  if [ ! -e "${DOTFILES_DIR}"/custom-config/"$1" ]; then
    cp -rf "${SOURCE_DIR}"/"$1" "${DOTFILES_DIR}"/custom-config/"$1"
  fi

  if [ ! -e "${DOTFILES_DIR}"/custom-config/"$1"/install ]; then
    ln -sf "${DOTFILES_DIR}"/custom-config/"$1" "${to}"
  fi
}

#==========================================
# Delete existing dot files and folders
#==========================================
rm -rf ~/.gitconfig >/dev/null 2>&1
rm -rf ~/.xprofile >/dev/null 2>&1
rm -rf ~/.Xresources >/dev/null 2>&1
rm -rf ~/.Xresources.d >/dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/polybar/modules/custom.conf >/dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/polybar/polybars/custom.conf >/dev/null 2>&1

#==========================================
# Create symlinks in the home folder
# Allow overriding with files of matching names in the custom-config dir
#==========================================
touch ~/.gitconfig >/dev/null 2>&1
touch ~/.xprofile >/dev/null 2>&1
touch ~/.Xresources >/dev/null 2>&1
touch "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/polybar/modules/custom.conf >/dev/null 2>&1
touch "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/polybar/modules/polybar.conf >/dev/null 2>&1

[ ! -d "${DOTFILES_DIR}"/custom-config/polybar/modules ] && mkdir -p "${DOTFILES_DIR}"/custom-config/polybar/modules
[ ! -d "${DOTFILES_DIR}"/custom-config/polybar/polybars ] && mkdir -p "${DOTFILES_DIR}"/custom-config/polybar/polybars

create_symlink alacritty
create_symlink gitconfig
create_symlink rofi
create_symlink xprofile
create_symlink Xresources
create_symlink Xresources.d
create_symlink "polybar/modules/custom.conf" "${XDG_CONFIG_HOME:-"${HOME}"/.config}/polybar/modules/custom.conf"
create_symlink "polybar/polybars/custom.conf" "${XDG_CONFIG_HOME:-"${HOME}"/.config}/polybar/polybars/custom.conf"

sudo chmod +x ~/.xprofile

printf "Setting up wm...\\n"

for script in "${DOTFILES_DIR}"/custom-config/**/install; do
  [ -e "${script}" ] || break
  [ -x "${script}" ] || {
    chmod +x "${script}"
  }
  ${script}
done

printf "Setting up git...\\n"

default_name=$(git config --global user.name)
default_email=$(git config --global user.email)

read -rp "Name [$default_name]: " name
read -rp "Email [$default_email]: " email

git config --global user.name "${name:-$default_name}"
git config --global user.email "${email:-$default_email}"
