#!/usr/bin/env bash

ROOT=$(dirname "$0")

printf "Setting up rofi themes...\\n"

rm -rf "${ROOT}"/rofi-themes
git clone https://github.com/ulises-jeremias/rofi-themes.git "${ROOT}"/rofi-themes
sudo rm -rf ~/.config/rofi/themes >/dev/null 2>&1
sudo rm -rf ~/.config/rofi/config.rasi >/dev/null 2>&1
mkdir -p ~/.config/rofi
ln -sf "${ROOT}"/rofi-themes/themes ~/.config/rofi/themes
