#!/usr/bin/env bash

ROOT=$(dirname "$0")

printf "Setting up rofi themes...\\n"

rm -rf "${ROOT}"/rofi-themes
git clone https://github.com/ulises-jeremias/rofi-themes.git "${ROOT}"/rofi-themes

rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi/themes >/dev/null 2>&1
rm -rf "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi/config.rasi >/dev/null 2>&1

mkdir -p "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi

ln -sf "${ROOT}"/rofi-themes/themes "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi/themes
ln -sf "${ROOT}"/apps.rasi "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi/apps.rasi
ln -sf "${ROOT}"/networks.rasi "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi/networks.rasi
ln -sf "${ROOT}"/tools.rasi "${XDG_CONFIG_HOME:-"${HOME}"/.config}"/rofi/tools.rasi
