#!/usr/bin/env bash

ROOT=$(dirname "$0")

SOURCE_DIR=$(realpath "${ROOT}")
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}"/.config}"

rm -rf "${XDG_CONFIG_HOME}"/i3 >/dev/null 2>&1
ln -sf "${SOURCE_DIR}" "${XDG_CONFIG_HOME}"/i3
