#!/usr/bin/env bash

create_symlink() {
    if [ -n "$(find $dotfiles_dir/custom-config -name $1)" ]; then
        ln -sf $dotfiles_dir/custom-config/$1 ~/.$1
    else
        cp -f $ROOT/$1 $dotfiles_dir/custom-config/$1
        ln -sf $dotfiles_dir/custom-config/$1 ~/.$1
    fi
}

ROOT=$(dirname $0)
dotfiles_dir="$ROOT/.."

#==========================================
# Delete existing dot files and folders
#==========================================
sudo rm -rf ~/.dotfiles.config.env > /dev/null 2>&1
sudo rm -rf ~/.gitconfig > /dev/null 2>&1
sudo rm -rf ~/.xprofile > /dev/null 2>&1
sudo rm -rf ~/.Xresources > /dev/null 2>&1

#==========================================
# Create symlinks in the home folder
# Allow overriding with files of matching names in the custom-config dir
#==========================================
touch ~/.dotfiles.config.env
touch ~/.gitconfig
touch ~/.xprofile
touch ~/.Xresources

create_symlink dotfiles.config.env
create_symlink gitconfig
create_symlink xprofile
create_symlink Xresources

sudo chmod +x ~/.xprofile

printf "Setting up git...\\n"

defaultName=$(git config --global user.name)
defaultEmail=$(git config --global user.email)
defaultGithub=$(git config --global github.user)

read -rp "Name [$defaultName]: " name
read -rp "Email [$defaultEmail]: " email
read -rp "Github username [$defaultGithub]: " github

git config --global user.name "${name:-$defaultName}"
git config --global user.email "${email:-$defaultEmail}"
git config --global github.user "${github:-$defaultGithub}"
