#!/usr/bin/env bash

set -e

ROOT="$(realpath "$(dirname "$0")")"
DOTFILES_DIR=$(realpath "${ROOT}")

#==========================================
# Make symlink for bin files
#==========================================
if [ ! -d "${HOME}/.local/bin" ]; then
  mkdir ~/.local/bin
fi

printf "Installing binaries... "

for bin_path in "${DOTFILES_DIR}"/bin/*; do
  bin=$(basename "${bin_path}")

  chmod +x "${bin_path}"
  rm -rf ~/.local/bin/"${bin}" >/dev/null 2>&1
  ln -sf "$(realpath "${bin_path}")" ~/.local/bin/"${bin}"
done

echo "Done."

#==========================================
# Execute dotfiles install strategy
#==========================================
if [[ -z "${SKIP_CONFIG_INSTALL}" ]]; then
  printf "Installing dotfiles... "

  for config_path in "${DOTFILES_DIR}"/config/*; do
    config=$(basename "${config_path}")
    "${DOTFILES_DIR}"/config/"${config}"/install
  done

  echo "Done."
fi

echo "Done."
