#!/usr/bin/env bash

set -e

ROOT="$(realpath "$(dirname "$0")")"
DOTFILES_DIR=$(realpath "${ROOT}")

#==========================================
# Make symlink for bin files
#==========================================
if [ ! -d "${HOME}/.local/bin" ]; then
  mkdir ~/.local/bin
fi

printf "Installing binaries... "

chmod +x "${DOTFILES_DIR}"/bin/install
"${DOTFILES_DIR}"/bin/install

echo "Done."

#==========================================
# Execute dotfiles install strategy
#==========================================
if [[ -z "${SKIP_CONFIG_INSTALL}" ]]; then
  printf "Installing dotfiles... "

  for config_path in "${DOTFILES_DIR}"/config/*; do
    config=$(basename "${config_path}")
    chmod +x "${DOTFILES_DIR}"/config/"${config}"/install
    "${DOTFILES_DIR}"/config/"${config}"/install
  done

  echo "Done."
fi

echo "Done."
