#!/usr/bin/env bash

ROOT=$(dirname "$0")

rm -rf ~/.zshrc > /dev/null 2>&1
rm -rf ~/.zsh_prompt > /dev/null 2>&1
rm -rf ~/.zsh_aliases > /dev/null 2>&1

ln -sf "${ROOT}"/zshrc ~/.zshrc
ln -sf "${ROOT}"/zsh_prompt ~/.zsh_prompt
ln -sf "${ROOT}"/zsh_aliases ~/.zsh_aliases
