#!/usr/bin/env sh

## Copyright (C) 2019-2020 Ulises Jeremias Cornejo Fandos
## Licensed under MIT
##
##     @script.name [OPTION] ARGUMENTS...
##
## Options:
##     -h, --help                            Help.
##     -c, --clear                           Will remove existing dotfiles.
##     -u, --upgrade                         Will update dependencies anyway.
##         --nodeps                          Will not install dependencies.
##
##         --os=OS_NAME                      Operating System. Posible values: common | arch-linux | debian
##                                           where common is supposed to work correctly with any linux distro.
##                                           `common` is set as default value for this flag.
##         --wms=COMMA_SEPARATED_WMS         Window managers. Posible wms: i3, openbox
##         --log-file=LOG_FILE_PATH          Logs file path, is /tmp/install_progress_log_$(date +'%m-%d-%y_%H:%M:%S').txt by default.
##         --dotfiles-dir=OUTPUT_PATH        Dotfiles output dir, is ~/dotfiles by default.
##         --pkgs=COMMA_SEPARATED_DEPS       Dependencies to install.
##

ROOT=$(dirname $0)

source ${ROOT}/../util/opts/opts.sh || exit
source ${ROOT}/../util/logs.sh || exit

#==========================================
# Default argument values and preprocessing
#==========================================
os=${os:-"common"}
time_str=$(date +'%m-%d-%y_%H:%M:%S')
log_file=${log_file:-"/tmp/install_progress_log_$time_str.txt"}
dotfiles_dir=${dotfiles_dir:-"$HOME/dotfiles"}
wms=${wms:-""}

[ ! -f "${log_file}" ] && touch ${log_file}

if [ -n "${upgrade}" ]; then
    upgrade_flag="--upgrade"
fi

if [ -n "${clear}" ]; then
    clear_flag="--clear"
fi

#==========================================
# Install dependencies according to os
#==========================================
if [ ! -n "${nodeps}" ] && [ "${os}" != "" ]; then
    ${ROOT}/install-pkgs \
        --log-file=${log_file} ${upgrade_flag} --os=${os} \
        --pkgs=${pkgs}
fi

echo

#==========================================
# Install dotfiles according to os
#==========================================
${ROOT}/install-dotfiles --log-file=${log_file} --dotfiles-dir=${dotfiles_dir} --os=${os} --wms=${wms} ${clear_flag}

#==========================================
# Set zsh as the default shell
#==========================================
echo
sudo chsh -s /bin/zsh

#==========================================
# Give the user a summary of what has
# been installed
#==========================================
echo -e "\n====== Summary ======\n"
cat ${log_file}
echo
echo "Enjoy dotfiles :D"
rm ${log_file}
