#!/usr/bin/env bash

ROOT=$(dirname $0)

. $ROOT/../lib/log.sh

#==========================================
# Args declaration
#==========================================

. $ROOT/../lib/flags/declares.sh

variables["--os"]="os"
variables["-l"]="log_file";
variables["--log-file"]="log_file";

. $ROOT/../lib/flags/arguments.sh

#==========================================
# Default argument values and preprocessing
#==========================================

os=${os:-"arch-linux"}
time_str=$(date +'%m-%d-%y_%H:%M:%S')
log_file=${log_file:-"$HOME/install_progress_log_$time_str.txt"}

[ ! -f "$log_file" ] && touch $log_file

if has_param '-u' "$@" || has_param '--upgrade' "$@"; then
    upgrade_flag="-u"
fi

$ROOT/install-pkgs -l $log_file ${upgrade_flag} --os ${os}
