#!/usr/bin/env bash

ROOT=$(dirname $0)

. $ROOT/../lib/log.sh

#==========================================
# Args declaration
#==========================================

. $ROOT/../lib/flags/declares.sh

variables["--os"]="os"
variables["-l"]="log_file";
variables["--log-file"]="log_file";
variables["--dotfiles-dir"]="dotfiles_dir";

. $ROOT/../lib/flags/arguments.sh

#==========================================
# Default argument values and preprocessing
#==========================================

os=${os:-"arch-linux"}
time_str=$(date +'%m-%d-%y_%H:%M:%S')
log_file=${log_file:-"/tmp/install_progress_log_$time_str.txt"}
dotfiles_dir=${dotfiles_dir:-"$HOME/dotfiles"}

[ ! -f "$log_file" ] && touch $log_file

if has_param '-u' "$@" || has_param '--upgrade' "$@"; then
    upgrade_flag="-u"
fi

#==========================================
# Install dependencies according to os
#==========================================
if ! has_param '--no-deps' "$@"; then
    $ROOT/install-pkgs \
        -l $log_file ${upgrade_flag} --os ${os} \
        --pkgs polybar,rofi,dbus-python,picom,zsh,networkmanager-dmenu-git,jgmenu,numix-circle-icon-theme-git,skippy-xd-git
fi

echo

#==========================================
# Install dotfiles according to os
#==========================================
$ROOT/install-dotfiles -l $log_file --os ${os} --dotfiles-dir ${dotfiles_dir}
