#!/usr/bin/env bash

git clone https://github.com/firecat53/networkmanager-dmenu /tmp/networkmanager-dmenu
[ ! -d ~/.local/bin ] && mkdir ~/.local/bin
cp /tmp/networkmanager-dmenu/networkmanager_dmenu ~/.local/bin
chmod +x dots-scripts networkmanager_dmenu
