#!/usr/bin/env bash

sudo apt install -y build-essential
sudo apt-get install -y g++ libgtk-3-dev gtk-doc-tools gnutls-bin valac intltool libpcre2-dev libglib3.0-cil-dev libgnutls28-dev libgirepository1.0-dev libxml2-utils gperf libtool
git clone https://github.com/thestinger/vte-ng.git /tmp/vte-ng
echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"
pushd /tmp/vte-ng || exit
git checkout 0.56.2.a
sudo make && sudo make install
popd || exit
git clone --recursive https://github.com/thestinger/termite.git /tmp/termite
pushd /tmp/termite || exit
sudo make && sudo make install
sudo ldconfig
popd || exit
