#!/usr/bin/env bash

fetch_pkg() {
    if [ $(pacman -Ss $1 | wc -l) -ne 0 ]; then
        return 0
    elif [ $(git ls-remote https://aur.archlinux.org/$1.git | wc -l) -ne 0 ]; then
        return 0
    else
        return 1
    fi
}

aur_install() {
    rm -rf /tmp/$1
    repo=$1
    if ! fetch_pkg $repo; then
        repo="$1-git"
    fi
    remote=https://aur.archlinux.org/$repo.git
    git clone $remote /tmp/$repo > /dev/null
    pushd /tmp/$repo
    yes | makepkg -si
    res=$?
    popd
    return $res
}

pkg_install() {
    sudo pacman --noconfirm -S $1 || aur_install $1
}

pkg_exists() {
    repo=$1
    git_repo="$1-git"

    if fetch_pkg $repo || fetch_pkg $git_repo; then
        return 0
    else
        return 1
    fi
}
