#!/usr/bin/env bash

ROOT=$(realpath "${ROOT}")
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}"/.config}"

printf "Setting up alacritty themes...\\n"

rm -rf "${ROOT}"/alacritty-theme
git clone https://github.com/eendroroy/alacritty-theme "${ROOT}"/alacritty-theme
rm -rf "${XDG_CONFIG_HOME}"/alacritty/themes >/dev/null 2>&1
mkdir -p "${XDG_CONFIG_HOME}"/alacritty
ln -sf "${ROOT}"/alacritty-theme/themes "${XDG_CONFIG_HOME}"/alacritty/themes
