name: AUR Publish - Development version

on:
  push:
    branches:
      - master

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Dotfiles
        uses: actions/checkout@v2

      - name: Replace PKGBUILD with correct file
        run: mv PKGBUILD.dev PKGBUILD

      - name: Publish AUR package
        uses: guumaster/aur-publish-docker-action@v1
        with:
          pkgname: dots-git
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
