name: AUR Publish - Development version

on:
  push:
    branches:
      - master

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Dotfiles
        uses: actions/checkout@v2

      - name: Publish AUR package
        uses: ulises-jeremias/github-actions-aur-publish@v1.0.1
        with:
          pkgname: dots-git
          pkgbuild: ./PKGBUILD.dev
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          update_pkgver: true
