name: AUR Publish - Development version

on:
  push:
    tags:
      - v*

  schedule:
    - cron: "31 1,12 * * *"

jobs:
  ci:
    name: CI Checks
    uses: ./.github/workflows/ci.yml

  aur-publish:
    needs:
      - ci

    runs-on: ubuntu-latest
    
    concurrency: unstable
    
    environment:
      name: unstable
      url: https://aur.archlinux.org/packages/dots-git

    steps:
      - name: Checkout Latest Dotfiles
        uses: actions/checkout@v2

      - name: Override PKGBUILD
        run: mv PKGBUILD.dev PKGBUILD

      - name: Publish AUR package
        uses: ulises-jeremias/github-actions-aur-publish@v1
        with:
          pkgname: dots-git
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          update_pkgver: true
