name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

  schedule:
    - cron: "31 1,12 * * *"

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  clone-and-install:
    name: Clone and Install
    uses: ./.github/workflows/clone-and-install.yml

  lint:
    name: Super Linter
    uses: ./.github/workflows/lint.yml

  todo:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: TODO
    uses: ./.github/workflows/todo.yml
