name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    uses: ./.github/workflows/shellcheck.yml

  markdownlint:
    name: Markdown Lint
    uses: ./.github/workflows/markdownlint.yml

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: ./.github/workflows/todo.yml
