name: Continuous Integration

concurrency:
   group: ci-${{ github.event.number }}
   cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

  schedule:
    - cron: "31 1,12 * * *"

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    uses: ./.github/workflows/shellcheck.yml

  markdownlint:
    name: Markdown Lint
    uses: ./.github/workflows/markdownlint.yml

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: ./.github/workflows/todo.yml
