name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

  schedule:
    - cron: "31 1,12 * * *"

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Super Linter
    uses: ./.github/workflows/lint.yml

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: ./.github/workflows/todo.yml
