name: Deploy Docs

on:
  push:
    branches:
      - master
    tags:
      - v*
      - git-v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Wiki Content
      uses: actions/checkout@v4
      with:
        repository: ulises-jeremias/dotfiles.wiki
        path: docs

    - name: Checkout github-wikito-converter
      uses: actions/checkout@v4
      with:
        repository: yakivmospan/github-wikito-converter
        path: github-wikito-converter

    - name: Build and Install github-wikito-converter globally
      run: |
        cd github-wikito-converter
        npm install
        npm run build
        cd ..

    - name: Build Docs
      run: |
        mkdir public
        node ./github-wikito-converter/dist/cli/gwtc.js --file-name index --output ./public --toc-level 4 ./docs

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public