name: Shellcheck

on:
  pull_request:
    branches:
      - master

  workflow_call:

jobs:
  shellcheck:
    name: Shellcheck

    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: error
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC1091 -e SC2034 -e SC2154 -e SC1071
