name: Task Checker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  task_sync:
    name: Task sync

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Begin CI...
        uses: actions/checkout@v6

      - name: Task list to Issue
        uses: alstr/todo-to-issue-action@v5
        id: task_sync
