#!/usr/bin/env bash

SOURCE_DIR="$(realpath "$(dirname "$0")")"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}"/.config}"

rm -rf "${XDG_CONFIG_HOME}"/networkmanager-dmenu/config.ini > /dev/null 2>&1
mkdir "${XDG_CONFIG_HOME}"/networkmanager-dmenu > /dev/null 2>&1
ln -sf "${SOURCE_DIR}"/config.ini "${XDG_CONFIG_HOME}"/networkmanager-dmenu/config.ini
