#!/usr/bin/env bash

ROOT=$(dirname "$0")

sudo rm -rf "${XDG_CONFIG_HOME}"/networkmanager-dmenu/config.ini > /dev/null 2>&1

mkdir "${XDG_CONFIG_HOME}"/networkmanager-dmenu > /dev/null 2>&1

ln -sf "${ROOT}"/config.ini "${XDG_CONFIG_HOME}"/networkmanager-dmenu/config.ini
